-- =======================
-- AIRLINE RESERVATION SYSTEM SCHEMA
-- =======================

-- AIRLINE
CREATE TABLE airline (
  airline_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airline_name VARCHAR2(100) NOT NULL,
  contact_info VARCHAR2(200)
);

-- AIRPLANE
CREATE TABLE airplane (
  airplane_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airline_id NUMBER NOT NULL REFERENCES airline(airline_id),
  model VARCHAR2(50) NOT NULL,
  capacity NUMBER NOT NULL CHECK (capacity > 0)
);

-- AIRPORT
CREATE TABLE airport (
  airport_id CHAR(3) PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  city VARCHAR2(50) NOT NULL,
  country VARCHAR2(50) NOT NULL
);

-- FLIGHT
CREATE TABLE flight (
  flight_id VARCHAR2(12) PRIMARY KEY,
  airplane_id NUMBER NOT NULL REFERENCES airplane(airplane_id),
  origin_airport_id CHAR(3) NOT NULL REFERENCES airport(airport_id),
  destination_airport_id CHAR(3) NOT NULL REFERENCES airport(airport_id),
  departure_utc TIMESTAMP WITH TIME ZONE NOT NULL,
  arrival_utc   TIMESTAMP WITH TIME ZONE NOT NULL,
  price NUMBER(10,2) NOT NULL CHECK (price >= 0),
  seats_total NUMBER NOT NULL CHECK (seats_total > 0),
  seats_available NUMBER NOT NULL CHECK (seats_available >= 0),
  CONSTRAINT chk_src_dst CHECK (origin_airport_id <> destination_airport_id),
  CONSTRAINT chk_arr_after_dep CHECK (arrival_utc > departure_utc)
);

CREATE INDEX idx_flight_route ON flight(origin_airport_id, destination_airport_id, departure_utc);

-- PASSENGER
CREATE TABLE passenger (
  passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(120) NOT NULL,
  contact VARCHAR2(20),
  email VARCHAR2(200) UNIQUE
);

-- BOOKING
CREATE TABLE booking (
  booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passenger_id NUMBER NOT NULL REFERENCES passenger(passenger_id),
  flight_id VARCHAR2(12) NOT NULL REFERENCES flight(flight_id),
  seat_no VARCHAR2(8),
  booking_date TIMESTAMP DEFAULT SYSTIMESTAMP,
  status VARCHAR2(16) DEFAULT 'CONFIRMED' CHECK (status IN ('CONFIRMED','CANCELLED')),
  fare_paid NUMBER(10,2) NOT NULL CHECK (fare_paid >= 0)
);

CREATE INDEX idx_booking_flight ON booking(flight_id);
CREATE INDEX idx_booking_passenger ON booking(passenger_id);

-- PAYMENT (1:1 with booking)
CREATE TABLE payment (
  payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id NUMBER UNIQUE NOT NULL REFERENCES booking(booking_id),
  amount NUMBER(10,2) NOT NULL CHECK (amount >= 0),
  method VARCHAR2(30),
  status VARCHAR2(16) DEFAULT 'COMPLETED' CHECK (status IN ('COMPLETED','FAILED','PENDING','REFUNDED')),
  payment_date TIMESTAMP DEFAULT SYSTIMESTAMP
);
